"""
Strategy Module for FundingPips Trading System

Base strategy class and implementations.
All strategies must inherit from BaseStrategy.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from typing import Optional, List, Dict
import pandas as pd
import numpy as np


@dataclass
class Signal:
    """Trading signal generated by a strategy"""
    
    instrument: str
    direction: int  # 1 = long, -1 = short, 0 = flat
    strength: float  # 0.0 to 1.0 (confidence level)
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    timestamp: datetime = None
    metadata: Dict = None
    
    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.now()
        if self.metadata is None:
            self.metadata = {}


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    
    All strategies must implement:
    - generate_signal(): Generate trading signal for current bar
    - name(): Strategy name for identification
    """
    
    def __init__(self, config: dict = None):
        self.config = config or {}
        self.name = self.__class__.__name__
    
    @abstractmethod
    def generate_signal(
        self,
        data: pd.DataFrame,
        current_time: datetime,
        current_position: int = 0
    ) -> Signal:
        """
        Generate trading signal based on available data
        
        Args:
            data: Historical OHLCV data up to current_time
            current_time: Current timestamp (decision point)
            current_position: Current position (1=long, -1=short, 0=flat)
        
        Returns:
            Signal object with trading decision
        
        IMPORTANT: Only use data available at current_time (no look-ahead!)
        """
        pass
    
    def on_trade(self, trade_info: dict):
        """Callback when a trade is executed"""
        pass
    
    def reset(self):
        """Reset strategy state (called at start of new backtest/run)"""
        pass


class TrendFollowingStrategy(BaseStrategy):
    """
    Trend Following Strategy with Volatility Overlay
    
    Entry Rules:
    - Fast MA crosses above Slow MA → Long signal
    - Fast MA crosses below Slow MA → Short signal
    - ATR filter: Only trade if volatility > threshold
    
    Exit Rules:
    - Price crosses below/above exit MA
    - Stop loss hit (ATR-based)
    
    Position Sizing:
    - Volatility-targeted: Size inversely proportional to ATR
    """
    
    def __init__(self, config: dict = None):
        super().__init__(config)
        
        # Strategy parameters
        self.fast_period = config.get('fast_period', 20)
        self.slow_period = config.get('slow_period', 50)
        self.exit_period = config.get('exit_period', 10)
        self.atr_period = config.get('atr_period', 14)
        self.volatility_filter = config.get('volatility_filter', True)
        self.min_volatility = config.get('min_volatility', 0.005)
        self.atr_multiplier_sl = config.get('atr_multiplier_sl', 2.0)
        self.risk_per_trade = config.get('risk_per_trade', 0.005)
        
        self.name = f"TrendFollowing(Fast={self.fast_period},Slow={self.slow_period})"
    
    def generate_signal(
        self,
        data: pd.DataFrame,
        current_time: datetime,
        current_position: int = 0
    ) -> Signal:
        """Generate trend following signal"""
        
        # Ensure we have enough data
        if len(data) < self.slow_period + 10:
            return Signal(
                instrument=data.columns[0] if isinstance(data.columns, pd.Index) else 'UNKNOWN',
                direction=0,
                strength=0.0,
                metadata={'reason': 'Insufficient data'}
            )
        
        # Get current price
        current_price = data['close'].iloc[-1]
        
        # Calculate moving averages (using data up to current bar only)
        fast_ma = data['close'].rolling(window=self.fast_period).mean().iloc[-1]
        slow_ma = data['close'].rolling(window=self.slow_period).mean().iloc[-1]
        exit_ma = data['close'].rolling(window=self.exit_period).mean().iloc[-1]
        
        # Calculate ATR
        high = data['high']
        low = data['low']
        close_prev = data['close'].shift(1)
        
        tr1 = high - low
        tr2 = abs(high - close_prev)
        tr3 = abs(low - close_prev)
        true_range = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
        atr = true_range.rolling(window=self.atr_period).mean().iloc[-1]
        
        # Volatility filter
        if self.volatility_filter:
            volatility = data['close'].pct_change().rolling(20).std().iloc[-1]
            if volatility < self.min_volatility:
                # Low volatility - reduce position or stay flat
                if current_position != 0:
                    # Exit existing position
                    return Signal(
                        instrument='PORTFOLIO',
                        direction=0,
                        strength=1.0,
                        metadata={'reason': 'Low volatility filter'}
                    )
                else:
                    return Signal(
                        instrument='PORTFOLIO',
                        direction=0,
                        strength=0.0,
                        metadata={'reason': 'Low volatility filter'}
                    )
        
        # Determine signal direction
        prev_fast_ma = data['close'].rolling(window=self.fast_period).mean().iloc[-2]
        prev_slow_ma = data['close'].rolling(window=self.slow_period).mean().iloc[-2]
        
        # Check for crossover
        bullish_cross = (prev_fast_ma <= prev_slow_ma) and (fast_ma > slow_ma)
        bearish_cross = (prev_fast_ma >= prev_slow_ma) and (fast_ma < slow_ma)
        
        # Check for exit conditions
        exit_long = current_price < exit_ma and current_position == 1
        exit_short = current_price > exit_ma and current_position == -1
        
        # Generate signal
        if bullish_cross:
            direction = 1
            strength = min(1.0, (fast_ma - slow_ma) / slow_ma * 100)
            
            # Calculate stop loss (ATR-based)
            stop_loss = current_price - (self.atr_multiplier_sl * atr)
            
            return Signal(
                instrument='PORTFOLIO',
                direction=direction,
                strength=strength,
                entry_price=current_price,
                stop_loss=stop_loss,
                metadata={
                    'signal_type': 'bullish_cross',
                    'fast_ma': fast_ma,
                    'slow_ma': slow_ma,
                    'atr': atr
                }
            )
        
        elif bearish_cross:
            direction = -1
            strength = min(1.0, (slow_ma - fast_ma) / slow_ma * 100)
            
            # Calculate stop loss (ATR-based)
            stop_loss = current_price + (self.atr_multiplier_sl * atr)
            
            return Signal(
                instrument='PORTFOLIO',
                direction=direction,
                strength=strength,
                entry_price=current_price,
                stop_loss=stop_loss,
                metadata={
                    'signal_type': 'bearish_cross',
                    'fast_ma': fast_ma,
                    'slow_ma': slow_ma,
                    'atr': atr
                }
            )
        
        elif exit_long:
            return Signal(
                instrument='PORTFOLIO',
                direction=0,
                strength=1.0,
                metadata={'reason': 'exit_long', 'exit_ma': exit_ma}
            )
        
        elif exit_short:
            return Signal(
                instrument='PORTFOLIO',
                direction=0,
                strength=1.0,
                metadata={'reason': 'exit_short', 'exit_ma': exit_ma}
            )
        
        else:
            # No signal - maintain current position
            return Signal(
                instrument='PORTFOLIO',
                direction=current_position,
                strength=0.0,
                metadata={'reason': 'no_signal'}
            )


def get_strategy(strategy_type: str, config: dict = None) -> BaseStrategy:
    """Factory function to create strategy instances"""
    
    strategies = {
        'trend_following': TrendFollowingStrategy,
        # Add more strategies here as they are implemented
        # 'momentum': MomentumStrategy,
        # 'mean_reversion': MeanReversionStrategy,
    }
    
    if strategy_type not in strategies:
        raise ValueError(f"Unknown strategy type: {strategy_type}")
    
    return strategies[strategy_type](config)
